#ifndef QMATERIALLIB_GLOBAL_H
#define QMATERIALLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QMATERIALLIB_LIBRARY)
#  define QMATERIALLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QMATERIALLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QMATERIALLIB_GLOBAL_H
